import { sleep } from '@/lib/sleep'
import WebsocketConnection from '@/lib/websocket'


export async function testSymbols(socket: WebsocketConnection) {
  console.log()
  console.log('Aqui hauria d obrir NEAR:')
  socket.send('거래 KRW, BTC 마켓 디지털 자산 추가 (NEAR, YGG)')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir QUACK:')
  socket.send('거래 KRW, BTC 마켓 디지털 자산 추가 (QUACK)')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir YGG:')
  socket.send('거래 KRW, BTC 마켓 디지털 자산 추가 (LLLL, YGG)')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir IDEX:')
  socket.send('Circuits of Value(COVAL), IDEX(IDEX), Moss Carbon Credit(MCO2), Polkastarter(POLS), ShapeShift FOX Token(FOX), Spell Token(SPELL) and SuperFarm(SUPER) are launching on Coinbase Pro')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir IDEX:')
  socket.send('IDEX(IDEX), Moss Carbon Credit(MCO2), Polkastarter(POLS), ShapeShift FOX Token(FOX), Spell Token(SPELL) and SuperFarm(SUPER) are launching on Coinbase Pro')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir IDEX:')
  socket.send('Idex Coin(IDEX)is launching on Coinbase Pro')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir SPELL:')
  socket.send('Binance Will List Spell Token(SPELL) and TerraUSD(UST)')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir UST:')
  socket.send('Binance Will List Spell Token(LLLL) and TerraUSD(UST)')
  await sleep(1000)
  console.log()
  console.log('Aqui hauria d obrir SPELL:')
  socket.send('Binance Will List Spell Token(SPELL)')
}